version: '2'

tasks:
  build:
    cmds:
      - docker build -t nicolasritouet/sentiment-frontend frontend
      - docker build -t nicolasritouet/sentiment-backend backend
  run:
    cmds:
      - docker run -d -p 80:80 --name sentiment-frontend nicolasritouet/sentiment-frontend
      - docker run -d -p 3001:3001 --name sentiment-backend nicolasritouet/sentiment-backend
  push:
    cmds:
      - docker push nicolasritouet/sentiment-frontend
      - docker push nicolasritouet/sentiment-backend
  cleanup:
    cmds:
      - docker stop sentiment-frontend
      - docker rm sentiment-frontend
      - docker stop sentiment-backend
      - docker rm sentiment-backend
  test:
    cmds:
      - curl http://localhost
      - "curl -X POST http://localhost:3001 -H 'content-type: multipart/form-data' -F 'sentence=I love dolphins'"
  logs:
    cmds:
      - docker logs sentiment-frontend
      - docker logs sentiment-backend
  deploy:
    cmds:
      - kubectl apply -f k8s/frontend.yml --record
      - kubectl apply -f k8s/frontend-lb.yml --record
      - kubectl apply -f k8s/backend.yml --record
      - kubectl apply -f k8s/backend-lb.yml --record
  local:
    cmds:
      - kubectl expose deployment sentiment-backend --type=LoadBalancer
      - kubectl expose deployment sentiment-frontend-lb --type=LoadBalancer
  update-containers:
    cmds:
      - kubectl patch deployment sentiment-backend -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
      - kubectl patch deployment sentiment-frontend -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"