apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: sentiment-backend
        image: nicolasritouet/sentiment-backend
        ports:
        - containerPort: 3001