apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-frontend
  labels:
    app: sentiment-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentiment-frontend
  template:
    metadata:
      labels:
        app: sentiment-frontend
    spec:
      containers:
      - name: sentiment-frontend
        image: nicolasritouet/sentiment-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-frontend-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sentiment-frontend